# Generated by Django 5.0.6 on 2024-07-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_address_item_permanent_address_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='permanent_address_barangay',
        ),
        migrations.RemoveField(
            model_name='item',
            name='permanent_address_city',
        ),
        migrations.RemoveField(
            model_name='item',
            name='permanent_address_house_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='permanent_address_province',
        ),
        migrations.RemoveField(
            model_name='item',
            name='permanent_address_street',
        ),
        migrations.RemoveField(
            model_name='item',
            name='permanent_address_subdivision',
        ),
        migrations.RemoveField(
            model_name='item',
            name='permanent_address_zip_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='residential_address_barangay',
        ),
        migrations.RemoveField(
            model_name='item',
            name='residential_address_city',
        ),
        migrations.RemoveField(
            model_name='item',
            name='residential_address_house_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='residential_address_province',
        ),
        migrations.RemoveField(
            model_name='item',
            name='residential_address_street',
        ),
        migrations.RemoveField(
            model_name='item',
            name='residential_address_subdivision',
        ),
        migrations.RemoveField(
            model_name='item',
            name='residential_address_zip_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='telephone_no',
        ),
    ]
