# Generated by Django 5.0.6 on 2024-07-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_item_children_date_of_birth_item_children_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='children_name_extension',
            new_name='children_name',
        ),
    ]
