# Generated by Django 5.0.6 on 2024-07-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_children_name_extension_item_children_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='children_details',
        ),
    ]
