# Generated by Django 5.0.6 on 2024-07-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_item_children_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='father_first_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='father_middle_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='father_name_extension',
        ),
        migrations.RemoveField(
            model_name='item',
            name='father_surname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mother_maiden_first_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mother_maiden_middle_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mother_maiden_surname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='spouse_business_address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='spouse_employer_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='spouse_first_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='spouse_middle_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='spouse_occupation',
        ),
        migrations.RemoveField(
            model_name='item',
            name='spouse_surname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='spouse_telephone_no',
        ),
    ]
