# Generated by Django 5.0.6 on 2024-07-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_item_father_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gsis_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pagibig_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='per_barangay',
        ),
        migrations.RemoveField(
            model_name='item',
            name='per_city',
        ),
        migrations.RemoveField(
            model_name='item',
            name='per_house_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='per_province',
        ),
        migrations.RemoveField(
            model_name='item',
            name='per_street',
        ),
        migrations.RemoveField(
            model_name='item',
            name='per_subdivision',
        ),
        migrations.RemoveField(
            model_name='item',
            name='per_zipcode',
        ),
        migrations.RemoveField(
            model_name='item',
            name='philhealth_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='res_barangay',
        ),
        migrations.RemoveField(
            model_name='item',
            name='res_city',
        ),
        migrations.RemoveField(
            model_name='item',
            name='res_house_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='res_province',
        ),
        migrations.RemoveField(
            model_name='item',
            name='res_street',
        ),
        migrations.RemoveField(
            model_name='item',
            name='res_subdivision',
        ),
        migrations.RemoveField(
            model_name='item',
            name='res_zipcode',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sss_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='telephone_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tin_no',
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='bloodtype',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='business_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='employee_business',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gsis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='occupation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pag_ibig_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='philhealth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sss',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='agency_employee_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='civil_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
